import pandas as pd 

configfile: "config.yaml"

models = pd.read_csv(config['models'], keep_default_na=False)

rule all:
    input:
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_heatmap_truncated", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename']),
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_heatmap", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename']),
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_boxplot", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename']),
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_violinplot", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename']),
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_averageplot", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename']),
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_scatterplot", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename']),
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_logoplot", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename']),
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_density", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename']),
        expand("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_table", zip, gene=models['coding_gene'], status=models['status'], method=models['method'], start_res=models['start_res'], end_res=models['end_res'], model=models['model'], pdb_filename=models['pdb_filename'])

rule get_input_mutations:
    input:
        "{gene}/{status}/stability/mutatex_runs/{method}_{start_res}-{end_res}/{model}/saturation/mutation_list.txt",
        "{gene}/{status}/stability/mutatex_runs/{method}_{start_res}-{end_res}/{model}/saturation/results/mutation_ddgs/final_averages"
    output:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/mutation_list.txt",
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/final_averages")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation
        mkdir -p $working_dir
	    cd $working_dir

        ln -s ../../../../mutatex_runs/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/mutation_list.txt
        ln -s ../../../../mutatex_runs/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/results/mutation_ddgs/final_averages
        """

rule get_input_pdb:
    input:
        "{gene}/{status}/stability/mutatex_runs/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb",
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/mutation_list.txt",
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/final_averages"
    output:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation
        mkdir -p $working_dir
            cd $working_dir

        ln -s ../../../../mutatex_runs/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_model0_checked.pdb
        """

rule plot_heatmap:
    input:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    params:
        font_size=config['plot_params']['font_size'],
        n_res=config['plot_params']['n_res_plot']
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_heatmap")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_heatmap
        mkdir -p $working_dir
	    cd $working_dir
		
        {config[mutatex][env]}
        ddg2heatmap -p ../{wildcards.pdb_filename}_model0_checked.pdb\
            -l ../mutation_list.txt\
            -d ../final_averages\
            -c viridis\
            -f {params.font_size}\
	        -s {params.n_res}
        """
rule plot_heatmap_truncated:
    input:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    params:
        font_size=config['plot_params']['font_size'],
        n_res=config['plot_params']['n_res_plot'],
        min_energy=config['plot_params']['heatmap']['min_energy'],
        max_energy=config['plot_params']['heatmap']['max_energy']
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_heatmap_truncated")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_heatmap_truncated
        mkdir -p $working_dir
	    cd $working_dir

        {config[mutatex][env]}
        ddg2heatmap -p ../{wildcards.pdb_filename}_model0_checked.pdb\
            -l ../mutation_list.txt\
            -d ../final_averages\
            -c viridis\
            -f {params.font_size}\
            -s {params.n_res} -n {params.min_energy} -x {params.max_energy}

	"""

rule plot_box:
    input:
	"{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    params:
        n_res=config['plot_params']['n_res_plot'],
        min_energy=config['plot_params']['distribution_plots']['min_energy'],
        max_energy=config['plot_params']['distribution_plots']['max_energy']
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_boxplot")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_boxplot
	    mkdir -p $working_dir        
	    cd $working_dir
		
        {config[mutatex][env]}
        ddg2distribution -p ../{wildcards.pdb_filename}_model0_checked.pdb\
                    -l ../mutation_list.txt\
                    -d ../final_averages\
                    -s {params.n_res} -n {params.min_energy} -x {params.max_energy}\
                    -T box\
		            -u 20
        """

rule plot_violin:
    input:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    params:
        n_res=config['plot_params']['n_res_plot'],
        min_energy=config['plot_params']['distribution_plots']['min_energy'],
        max_energy=config['plot_params']['distribution_plots']['max_energy']
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_violinplot")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_violinplot
        mkdir -p $working_dir
	    cd $working_dir
		
        {config[mutatex][env]}
        ddg2distribution -p ../{wildcards.pdb_filename}_model0_checked.pdb\
                    -l ../mutation_list.txt\
                    -d ../final_averages\
                    -s {params.n_res} -n {params.min_energy} -x {params.max_energy}\
                    -T violin\
		            -u 20
        """

rule plot_average:
    input:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    params:
        n_res=config['plot_params']['n_res_plot'],
        min_energy=config['plot_params']['distribution_plots']['min_energy'],
        max_energy=config['plot_params']['distribution_plots']['max_energy']
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_averageplot")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_averageplot
        mkdir -p $working_dir
	    cd $working_dir
		
        {config[mutatex][env]}
        ddg2distribution -p ../{wildcards.pdb_filename}_model0_checked.pdb\
                    -l ../mutation_list.txt\
                    -d ../final_averages\
                    -s {params.n_res} -n {params.min_energy} -x {params.max_energy}\
                    -T average\
		            -u 20
        """

rule plot_scatter:
    input:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    params:
        n_res=config['plot_params']['n_res_plot'],
        min_energy=config['plot_params']['distribution_plots']['min_energy'],
        max_energy=config['plot_params']['distribution_plots']['max_energy']
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_scatterplot")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_scatterplot
        mkdir -p $working_dir
	    cd $working_dir
		
        {config[mutatex][env]}
        ddg2distribution -p ../{wildcards.pdb_filename}_model0_checked.pdb\
                    -l ../mutation_list.txt\
                    -d ../final_averages\
                    -s {params.n_res} -n {params.min_energy} -x {params.max_energy}\
                    -T scatter\
		            -u 20
        """
rule plot_logo:
    input:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    params:
        font_size=config['plot_params']['font_size'],
        n_res=config['plot_params']['n_res_plot'],
        threshold=config['plot_params']['logo_plot']['destabilizing_threshold']
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_logoplot")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_logoplot
        mkdir -p $working_dir
	    cd $working_dir
		
        {config[mutatex][env]}
        ddg2logo -p ../{wildcards.pdb_filename}_model0_checked.pdb\
                    -l ../mutation_list.txt\
                    -d ../final_averages\
                    -s {params.n_res}\
		            -f {params.font_size}\
                    -t {params.threshold}\
		            -x 10
        """
    
rule plot_density:
    input:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_density")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_density
        mkdir -p $working_dir
	    cd $working_dir
		
        {config[mutatex][env]}
        ddg2density -p ../{wildcards.pdb_filename}_model0_checked.pdb\
                    -l ../mutation_list.txt\
                    -d ../final_averages
        """

rule write_table:
    input:
        "{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_model0_checked.pdb"
    output:
        directory("{gene}/{status}/stability/mutatex_analyses/{method}_{start_res}-{end_res}/{model}/saturation/{pdb_filename}_table")
    shell:
        """
        working_dir={wildcards.gene}/{wildcards.status}/stability/mutatex_analyses/{wildcards.method}_{wildcards.start_res}-{wildcards.end_res}/{wildcards.model}/saturation/{wildcards.pdb_filename}_table
        mkdir -p $working_dir
	    cd $working_dir
		
        {config[mutatex][env]}
        ddg2excel -p ../{wildcards.pdb_filename}_model0_checked.pdb\
                    -l ../mutation_list.txt\
                    -d ../final_averages
        
	    ddg2excel -p ../{wildcards.pdb_filename}_model0_checked.pdb\
                    -l ../mutation_list.txt\
                    -d ../final_averages\
		            -F csv
        """


