reference: "references.csv"

pdb_dir: "../../input_pdb"
csv_dir: "../../input_csv"
out_dir: "output_folder"

mutatex:
    skip_repair: False
    foldx_exe: "/usr/local/foldx5_2021/foldx"

mutation_list: |
        N
        A
        C

mutate_runfile: |
        command=BuildModel
        pdb=$PDBS$
        mutant-file=individual_list.txt
        water=-CRYSTAL
        numberOfRuns=$NRUNS$
        complexWithDNA=true

repair_runfile: |
        command=RepairPDB
        pdb=$PDBS$
        temperature=298
        water=-CRYSTAL
        complexWithDNA=true

interface_runfile: |
        command=AnalyseComplex
        pdb-list=$PDBLIST$
        water=-CRYSTAL
        temperature=298
        pH=7
        ionStrength=0.050
        vdwDesign=2
        pdbHydrogens=false


