import pandas as pd
import numpy as np
import glob
import os
import logging
import mutatex
import shutil

configfile: 'config.yaml'
reference = pd.read_csv(config['reference'], keep_default_na=False)

assert all(list(map(os.path.isfile,config["csv_dir"]+"/"+reference["protein_name"]+reference["chain_protein"]+reference["chain_peptide"]+".csv"))), "Each pdb must have a CSV mutations table associated. The table name must contain the following wildcards: protein_name, chain_protein and chain_peptide (e.g., ankbab.csv)."

rule all:
    input:
        expand("%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name}/{restraints}/{scan}/mutations.tar.gz" %config["out_dir"],
                    zip,
                    protein_name=reference["protein_name"],
                    PDB=reference["PDB"],
                    chain_protein=reference["chain_protein"],
                    chain_peptide=reference["chain_peptide"],
                    aa_protein=reference["aa_protein"],
                    aa_peptide=reference["aa_peptide"],
                    method=reference["method"],
                    model_name=reference["model_name"],
                    scan=reference["scan"],
                    restraints=reference["restraints"])

rule input_files:
    input:
        pdb=lambda wcs: config["in_dir"]+"/"+reference.set_index(["protein_name","method","PDB","chain_protein","chain_peptide","aa_protein","aa_peptide","restraints","model_name","scan"]).loc[(wcs.protein_name,wcs.method,wcs.PDB,wcs.chain_protein,wcs.chain_peptide,wcs.aa_protein,wcs.aa_peptide,wcs.restraints,wcs.model_name,wcs.scan), "pdb_file"],
        csv=lambda wcs: config["csv_dir"]+"/"+wcs.protein_name+wcs.chain_protein+wcs.chain_peptide+".csv"
    output:
        link_pdb="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/{protein_name}_{PDB}.pdb" %config["out_dir"],
        mutate="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/mutate_runfile_template.txt" %config["out_dir"],
        interface="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/interface_runfile_template.txt" %config["out_dir"],
        repair="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/repair_runfile_template.txt" %config["out_dir"],
        mutation_list="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/mutation_list.txt" %config["out_dir"],
        poslist="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/poslist.txt" %config["out_dir"],
        readme="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/README_mutatex_run" %config["out_dir"]
    params:
        workflow_dir=os.path.abspath(os.path.dirname(workflow.snakefile))
    run:
        out_dir=config["out_dir"]+"/"+wildcards.method+"_"+wildcards.protein_name+"_"+wildcards.PDB+""+wildcards.chain_protein+""+wildcards.chain_peptide+"_"+wildcards.aa_protein+"_"+wildcards.aa_peptide+"/"+wildcards.model_name+"/"+wildcards.restraints+"/"+wildcards.scan+"/"
        shutil.copy2(input.pdb, out_dir)
        os.symlink(os.path.abspath(glob.glob(out_dir+"/*.pdb")[0]), output.link_pdb)
        with open(output.mutate,'w') as mutate:
            mutate.write(config["mutate_runfile"])
        with open(output.interface,'w') as interface:
            interface.write(config["interface_runfile"])
        with open(output.repair,'w') as repair:
            repair.write(config["repair_runfile"])
        if "WT residue" in pd.read_csv(input.csv) and "Position" in pd.read_csv(input.csv) and "Mutated residue" in pd.read_csv(input.csv):
            my_col=pd.read_csv(input.csv)[["WT residue", "Position", "Mutated residue"]].set_index("Position").loc[int(wildcards.aa_peptide.rpartition("-")[0]):int(wildcards.aa_peptide.rpartition("-")[2])].dropna().reset_index().apply(lambda x: '%s%s%s' % (x["WT residue"], int(x["Position"]), x["Mutated residue"]),axis=1)
        else:
            my_col=pd.read_csv(input.csv)[pd.read_csv(input.csv)["Mutation"].str.contains('|'.join(str(i) for i in range(int(wildcards.aa_peptide.rpartition("-")[0]),int(wildcards.aa_peptide.rpartition("-")[2])+1)))]["Mutation"].str.replace("p","")
        mutlist=my_col.apply(lambda x: "%s" % (x[-1:])).drop_duplicates().to_csv(output.mutation_list, index=False, header=False)
        poslist=my_col.apply(lambda x: "%s%s%s" % (x[0],wildcards.chain_peptide.upper(),x[1:-1])).drop_duplicates().to_csv(output.poslist, index=False, header=False)

        read_content=f"""# This directory contains a custom scanning run performed with mutatex. This directory was generated by the following Snakemake pipeline:

# {params.workflow_dir}

# The input PDB file has been copied from:

# {input.pdb}

# In order to run it, the following steps are required:
# source virtual environment
. /usr/local/envs/mutatex/bin/activate

# A symbolic link is also required to avoid problems with files having multiple dots in the filename
ln -s {input.pdb} {output.link_pdb}

"""
        with open(output.readme, "w") as readme:
            readme.write(read_content)
 
rule mutatex_scan:
    input:
        link_pdb="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/{protein_name}_{PDB}.pdb" %config["out_dir"],
        mutate="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/mutate_runfile_template.txt" %config["out_dir"],
        interface="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/interface_runfile_template.txt" %config["out_dir"],
        repair="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/repair_runfile_template.txt" %config["out_dir"],
        mutation_list="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/mutation_list.txt" %config["out_dir"],
        poslist="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/poslist.txt" %config["out_dir"],
        readme="%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/README_mutatex_run" %config["out_dir"]
    output:
        "%s/{method}_{protein_name}_{PDB}{chain_protein}{chain_peptide}_{aa_protein}_{aa_peptide}/{model_name,.*}/{restraints,.*}/{scan,.*}/mutations.tar.gz" %config["out_dir"]
    params:
        foldx_exe=config["mutatex"]["foldx_exe"],
        skip_repair="-S" if config["mutatex"]["skip_repair"] == True else "",
    threads:
        1
    shell:
        """
        set +u; source /usr/local/envs/mutatex/bin/activate; set -u
        cd {config[out_dir]}/{wildcards.method}_{wildcards.protein_name}_{wildcards.PDB}{wildcards.chain_protein}{wildcards.chain_peptide}_{wildcards.aa_protein}_{wildcards.aa_peptide}/{wildcards.model_name}/{wildcards.restraints}/{wildcards.scan}/
        echo -e "# mutatex command\nmutatex $(basename {input.link_pdb}) -q $(basename {input.poslist}) {params.skip_repair} -m $(basename {input.mutation_list}) --foldx-version=suite5 --np {threads} -x {params.foldx_exe} -B -C deep -v -L -c -l >& log &" >> $(basename {input.readme})
        mutatex $(basename {input.link_pdb}) -q $(basename {input.poslist}) {params.skip_repair} -m $(basename {input.mutation_list}) --foldx-version=suite5 --np {threads} -x {params.foldx_exe} -B -C deep -v -L -c -l >& log 
        
        """
